# This is built on GitHub's "basic workflow to help you get started with Actions"

name: JSON validation CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
#      - name: ls
#        run: |
#          ls -l /github/workspace/
#          ls -l /github/workspace/schema_tools/validator/
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: main/schema_tools/validator/test_schema.json
          INPUT_JSONS: main/schema_tools/validator/test_invalid_schema.json,main/schema_tools/validator/test_valid_schema.json
