# This is built on GitHub's "basic workflow to help you get started with Actions"

name: JSON validation CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile yaml schema to JSON
        run: |
          pip install pyyaml
          python -c 'import json, yaml, sys; json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=2)' < AgContext.yaml > AgContext.json
          curl -L https://json-schema.org/draft-07/schema > jsonschema07.schema.json
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./jsonschema07.schema.json
          INPUT_JSONS: ./AgContext.json
